# These are supported funding model platforms
github: NickScherbakov
patreon: opensourceadvantage
open_collective: opensource-competitive-advantage
ko_fi: opensourceresearch
custom: https://opensourceadvantage.org/donate